[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "navio_blsct" 
version = "0.0.8"
description = "Python bindings for the Navio blsct library"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[project.urls]
Homepage = "https://github.com/nav-io/libblsct-bindings"
Repository = "https://github.com/nav-io/libblsct-bindings"

[tool.pytest.ini_options]
filterwarnings = [
  "ignore:.*SwigPy.*__module__ attribute:DeprecationWarning"
]
