name: 'Common: Check blsct.i cosiscency'

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'ffi/python/blsct/blsct.i'
      - 'ffi/ts/blsct.i'
  pull_request:
    paths:
      - 'ffi/python/blsct/blsct.i'
      - 'ffi/ts/blsct.i'

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v3
        with:
          clean: true

      - name: Run consistency check
        run: |
          ./script/blsct-i-consistency.sh 

