name: Publish Python doc

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-docs:
    runs-on: macos-14

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Python dependencies
        run: |
          pip install sphinx ghp-import

      - name: Build document
        run: |
          cd ffi/python/docs
          make html

      - name: Deploy document
        run: |
          cd ffi/python/docs
          ghp-import -n -f -b python-doc build/html
          git push --force origin python-doc 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

