name: Publish to PyPI

on:
  workflow_dispatch:

jobs:
  build_wheels:
    strategy:
      matrix:
        os: ["ubuntu-24.04", "macos-15"]
        python-version: ["3.12", "3.13"]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          clean: true

      - name: Clean up workspace
        run: git clean -xdf

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        run: pip install cibuildwheel twine

      - name: Install system dependencies
        run: |
          if [[ $RUNNER_OS == 'Linux' ]]; then
            sudo apt-get update && sudo apt-get install -y swig autoconf automake libtool pkg-config 
          elif [[ $RUNNER_OS == 'macOS' ]]; then
            brew install swig autoconf automake libtool pkg-config 
          fi

      - name: Build wheels with cibuildwheel
        run: |
          cd ffi/python
          if [ "${{ matrix.python-version }}" = "3.12" ]; then
            export CIBW_BUILD="cp312-*"
          elif [ "${{ matrix.python-version }}" = "3.13" ]; then
            export CIBW_BUILD="cp313-*"
          fi
          cibuildwheel --output-dir wheelhouse

      - name: Upload to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          cd ffi/python
          twine upload wheelhouse/*.whl

