name: 'Python: run unit tests'

on:
  workflow_dispatch:
  push:
    paths:
      - 'ffi/python/**'
    paths-ignore:
      - '.pytest_cache/**'
      - 'dist/**'
      - 'docs/**'
      - 'navio-core/**'
      - 'navio_blsct.egg-info/**'
      - 'venv/**'

jobs:
  test:
    strategy:
      matrix:
        os: ["ubuntu-24.04", "macos-15"]
        python-version: ["3.12", "3.13"]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install navio_blsct and pytest
        run: |
          pip install navio_blsct
          pip install pytest

      - name: Checkout tests only
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            ffi/python/tests

      - name: Run tests
        run: |
          cd ffi/python
          pytest tests
