name: 'Python: Publish doc website'

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'ffi/python/docs/source/**'
      - 'ffi/python/blsct/**'

permissions:
  contents: write

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Install system dependencies
        run: |
          if [[ $RUNNER_OS == 'Linux' ]]; then
            sudo apt-get update && sudo apt-get install -y swig autoconf automake libtool pkg-config 
          elif [[ $RUNNER_OS == 'macOS' ]]; then
            brew install swig autoconf automake libtool pkg-config 
          fi

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Python dependencies
        run: |
          pip install sphinx ghp-import setuptools build pytest

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Build and install the package
        run: |
          cd ffi/python
          python -m build
          pip install dist/*.whl

      - name: Build document
        run: |
          cd ffi/python/docs
          make html

      - name: Deploy Python docs to /python
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ffi/python/docs/build/html
          publish_branch: gh-pages
          destination_dir: python
          keep_files: true

