name: 'TypeScript: Publish doc website'

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'ffi/ts/docs/**'
      - '.github/workflows/ts-doc-website.yml'

permissions:
  contents: write

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: |
          cd ffi/ts
          npm install --ignore-scripts

      - name: Generate TypeDoc documentation
        run: |
          cd ffi/ts
          npm run docs

      - name: Deploy TypeScript docs to /ts
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ffi/ts/docs
          publish_branch: gh-pages
          destination_dir: ts
          keep_files: true
